name: randam-rgtm

run-name: Deploy by @{{ github.actor }}

on:
  issue_comment:
    types: [ created ]
  pull_request_review:
    types: [ submitted ]
  pull_request_review_comment:
    types: [ created ]

jobs:
  lgtm:
    runs-on: ubuntu-latest
    if: >-
        contains(github.event.comment.body, 'lgtm')　
        || contains(github.event.review.body, 'lgtm')
    steps:
      - run: echo test lgtm
